[pytest]
testpaths = Web/tests
            API/tests
pythonpath = .


markers =
    email: Email validation tests
    password: Password validation tests
    fullname: Full name validation tests
    role: Role-based signup tests
    schema: Schema validation tests
    auth: Authentication tests

# Patrones de nombres de archivos y funciones de test
python_files = test_*.py
python_classes = Test*
python_functions = test_*